-- CREATE DATABASE hemato;

DROP DATABASE 'admissions';

CREATE TABLE "admissions" (
"index" INTEGER,
  "N_AIH" VARCHAR(30),
  "UF_ZI" VARCHAR(30),
  "DT_INTER" VARCHAR(30),
  "DT_SAIDA" VARCHAR(30),
  "US_TOT" REAL,
  "DIAS_PERM" INTEGER,
  "ANO_CMPT" VARCHAR(30),
  "DIAG_PRINC" VARCHAR(30),
  "MORTE" INTEGER,
  "IDADE" INTEGER,
  "CNES" VARCHAR(30),
  "SEXO" VARCHAR(30),
  "ETNIA" VARCHAR(30),
  "COMPLEX" VARCHAR(30),
  "CAR_INT" VARCHAR(30),
  "MUNIC_RES" VARCHAR(30),
  "MUNIC_MOV" VARCHAR(30),
  "NASC" VARCHAR(30),
  "DESCR_CID" VARCHAR(30)
);
